# Generated by Django 4.2.16 on 2024-09-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('secondName', models.CharField(blank=True, max_length=255)),
                ('aboutSelf', models.TextField(blank=True)),
                ('dateBirth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
