# Generated by Django 4.2.16 on 2024-09-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='people',
            name='aboutSelf',
            field=models.TextField(blank=True, verbose_name='О себе (aboutSelf)'),
        ),
        migrations.AlterField(
            model_name='people',
            name='dateBirth',
            field=models.DateField(verbose_name='Дата рождения (dateBirth)'),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email (email)'),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя (name)'),
        ),
        migrations.AlterField(
            model_name='people',
            name='secondName',
            field=models.CharField(blank=True, max_length=255, verbose_name='Никнейм (secondName)'),
        ),
    ]
